<?php
	define('SUCCESS',0);
	define('User_Exist',-1);
	define('ParamNot_Array',-2);
	define('Array_KeyError',-3);
	define('Param_Null',-4);
	define('HTTPpost_Error',-5);
	define('Array_Keylack',-21);
	define('User_InfoError',-22);
	define('Add_InfoError',-23);
	define('authority_Error',-24);
	define('DB_Error',-25);
	define('Param_Error',-26);
	define('DataInfo_Exist',-27);
		
	define('Post_AddUser',-6);
	define('Post_getUser',-7);
	define('Post_addAProject',-8);
	define('Post_updateAProject',-9);
	define('Post_addProjectMember',-10);
	define('Post_delAProject',-11);
	define('Post_getProject',-12);
	define('Post_getProjectMember',-13);
	define('Post_addABug',-14);
	define('Post_delABug',-15);
	define('Post_tranfBugHand',-16);
	define('Post_getBug',-17);
	define('Post_getBugDispose',-18);
	define('Post_addaBugDispose',-19);
?>